baseURL = "yingyu5658-pages.github.io"
publishDir = "public"
title = "Concise"
description = "A concise hugo theme."
languageCode = "zh-CN"
theme = ["concise"]
pagination = { pagerSize = 25 }

[permalinks]
posts = ""

[params]
[[params.homepage.content]]
name = "文章归档"
url = "/post"

[[params.homepage.content]]
name = "友情链接"
url = "/links"

[[params.homepage.content]]
name = "关于"
url = "/about"

[[params.homepage.content]]
name = "RSS"
url = "/atom.xml"

[params.footer]
content = "Email: YOUR_EMAIL"

[markup.highlight]
noClasses = true 
style = "emacs"    #github、emacs、solarized-light 等

[outputFormats.RSS]
  baseName = "atom"
